export const projects = [
  {
    id: '01', category: 'Embedded Systems', title: 'STM32 Light & Temperature Monitor', subtitle: 'ADC · DMA · PWM · UART', chip: 'STM32F103', theme: 'green',
    description: 'Sensor-driven embedded control system for light and temperature monitoring with real-time feedback and threshold-based alerts.',
    tags: ['STM32F103', 'C', 'ADC', 'DMA', 'PWM', 'UART'],
    highlights: ['TIM3 TRGO triggers ADC1 dual-channel scans at 100 Hz; circular DMA removes the need for CPU polling.', 'An 8-sample moving average smooths readings before TIM2 Channel 3 PWM adjusts LED brightness.', 'Hysteresis prevents warning chatter near temperature thresholds; USART1 streams live sensor diagnostics.'],
    flow: ['Light + NTC', 'ADC / DMA', 'Filter', 'PWM / UART'],
    sourceNote: 'Project summary based on the documented design and implementation.',
    github: 'https://github.com/qsz746/light_thermistor_monitor',
    images: [
      { src: '/media/light-thermistor-monitor/hardware-setup.jpg', alt: 'STM32F103 hardware setup with sensor modules and breadboard wiring.', title: 'Hardware setup', layout: 'portrait' },
      { src: '/media/light-thermistor-monitor/serial-telemetry.png', alt: 'Serial telemetry showing light-sensor voltage and temperature readings in Tera Term.', title: 'Live sensor readings', layout: 'portrait', description: 'USART1 streams light-sensor voltage and temperature readings to Tera Term for real-time diagnostics.' },
    ],
    youtubeId: 'YT6KDgGeqMg',
    videoLayout: 'portrait',
    videoTitle: 'Light and temperature monitoring',
    videoDescription: 'Hardware demonstration of the sensor monitor.',
    video: '',
  },
  {
    id: '02', category: 'FPGA & Digital Design', title: 'DE1-SoC FPGA Song Player', subtitle: 'SystemVerilog · FSM · Audio', period: 'May 2025 – Jun 2025', chip: 'DE1-SoC', theme: 'blue',
    description: 'FPGA-based music player with synchronized playback control, memory sequencing, and audio output validation.',
    tags: ['SystemVerilog', 'FPGA', 'FSM', 'ModelSim', 'SignalTap', 'Quartus'],
    highlights: ['FSM-based playback controls coordinate clock division and memory-address sequencing.', 'Verified function and timing with ModelSim testbenches and SignalTap on-chip debugging.', 'Deployed through Quartus with a PicoBlaze processor for average-signal computation and LED display.'],
    flow: ['Playback Controls', 'Control FSM', 'Memory Sequencing', 'Audio Output'],
    sourceNote: 'Project summary based on the provided implementation description.',
    github: 'https://github.com/qsz746/simple_ipod',
    images: [
      { src: '/media/simple-ipod/DE1-SOC.jpg', alt: 'DE1-SoC FPGA song player connected to headphones and a keyboard.', title: 'DE1-SoC song player' },
    ],
    youtubeId: '1CN9ugxQNpI',
    videoTitle: 'FPGA audio playback',
    videoDescription: 'Playback demonstration on the DE1-SoC.',
    video: '',
  },
  {
    id: '03', category: 'FPGA & Digital Design', title: 'Nios DDS / LFSR / Clock Domain Lab', subtitle: 'Qsys · DDS · SignalTap', chip: 'NIOS / FPGA', theme: 'purple',
    description: 'Lab-scale direct digital synthesis system with waveform selection, LFSR modulation, and clock-domain synchronization.',
    tags: ['Nios', 'Qsys', 'DDS', 'LFSR', 'Clock Domains', 'SignalTap'],
    highlights: ['Combines DDS waveform selection, LFSR modulation, and synchronization across clock domains.', 'ModelSim simulations cover the 5-bit LFSR, DDS selector, and fast-to-slow clock-domain synchronizer.', 'SignalTap captures document DDS, modulation, and clock-domain signals on hardware.'],
    flow: ['Nios / Qsys', 'DDS', 'LFSR Modulation', 'Clock Domains'],
    sourceNote: 'Based on the GitHub repository and the simulation and SignalTap records in README.pdf.',
    github: 'https://github.com/qsz746/CPEN311-Lab-5-Nios-Qsys-Direct-Digital-Synthesis-LFSR-Modulations-Clock-Domains',
    images: [
      { src: '/media/digital-signal-synthesis/fsk-waveforms.jpg', alt: 'Waveform display with FSK selected and waveform controls visible.', title: 'FSK waveform display' },
    ],
    video: '',
  },
  {
    id: '04', category: 'FPGA & Digital Design', title: 'Lab 4 Memory / Decryption Controller', subtitle: '8051 Assembly · DE0-CV', chip: 'CV-8052', theme: 'sand',
    description: 'Display and control project implementing state-based output modes, switch-driven logic, and timed digital sequencing on the CV-8052.',
    tags: ['8051 Assembly', 'DE0-CV', 'Quartus Prime', 'CrossIDE'],
    highlights: ['Lab specification: SW2–SW0 select the display mode and KEY3 latches the selection.', 'Specified modes include static digits, left/right scrolling, blinking, digit-by-digit output, and greeting messages.', 'The lab specifies 1-second or 0.5-second intervals via SW3, plus a custom display mode.'],
    flow: ['Switches / KEY3', '8051 Program', 'Display Modes', 'HEX5–HEX0'],
    sourceNote: 'Based on the CPEN312 Lab 4 specification, with a hardware photo and project demonstration.',
    github: '',
    images: [
      { src: '/media/cv-8052-display-controller/de0-cv-board.png', alt: 'Altera DE0-CV running the CV-8052 display project with six illuminated seven-segment digits.', title: 'DE0-CV display', layout: 'portrait' },
    ],
    youtubeId: '5FxMfcI95cU',
    videoLayout: 'portrait',
    videoTitle: 'Student-number display',
    videoDescription: 'Student-number display running on the DE0-CV board.',
    video: '',
  },
  {
    id: '05', category: 'Embedded Systems', title: 'Smart Embedded Fan Control', subtitle: 'STM32F103 · PWM · Servo · OLED', chip: 'STM32F103', theme: 'green',
    coverTagline: 'CONTROL. OSCILLATE. DISPLAY.',
    description: 'Bare-metal embedded fan controller with GPIO-driven motion logic, PWM speed control, and real-time system feedback.',
    tags: ['Bare-metal C', 'STM32F103', 'PWM', 'FSM', 'I2C OLED'],
    highlights: [
      'TIM2/TIM3 PWM drives an SG90 servo and DC motor; GPIO and an H-bridge control motor direction.',
      'Debounced buttons and an FSM toggle auto-swing and set speed in steps from 0–100%.',
      'An I2C OLED displays live speed and key status.',
    ],
    flow: ['Buttons', 'Control State', 'PWM / GPIO', 'Servo + DC Motor'],
    sourceNote: 'Based on the implementation summary, hardware photos, wiring diagram, and project repository.',
    github: 'https://github.com/qsz746/Smart-Embedded-Fan-Control-System',
    images: [
      { src: '/media/smart-fan-controller/hardware-setup.png', alt: 'STM32F103 fan controller prototype with an OLED, SG90 servo, motor driver, and DC fan.', title: 'Fan controller prototype', layout: 'portrait' },
      { src: '/media/smart-fan-controller/wiring-diagram.png', alt: 'Wiring diagram showing the STM32, servo, motor driver, buttons, OLED, and ST-Link connections.', title: 'Hardware connections', description: 'The wiring diagram documents connections between the STM32F103, SG90 servo, motor driver, buttons, OLED, and ST-Link.' },
    ],
    video: 'https://youtube.com/shorts/WcJsg5XpFCQ',
    videoTitle: 'Smart fan demo',
    videoDescription: 'Two short motion demos showing the fan control and oscillation behavior.',
    videoLinks: [
      'https://youtube.com/shorts/WcJsg5XpFCQ',
      'https://youtube.com/shorts/qeEqCD0n21M',
    ],
  },
]

